#[macro_use]
extern crate criterion;
extern crate gcode_parser;
extern crate nom;

use criterion::Criterion;
use gcode_parser::tokenizer::Tokenizer;
use std::time::Duration;

// Attempt to represent a real-world case with a file containing mostly move tokens with some G0/
// G1 commands. This looks like something that might be generated by a CAM program
fn bench_lots_of_vec9(c: &mut Criterion) {
    let program = include_str!("./lots_of_vec9.ngc");

    c.bench_function("File containing mostly moves", move |b| {
        b.iter(|| {
            let tokenizer = Tokenizer::new_from_str(&program);

            tokenizer.tokenize().unwrap();
        })
    });
}

criterion_group!{
    name = lots_of_vec9;
    config = Criterion::default()
        .warm_up_time(Duration::from_millis(1000))
        .sample_size(100)
        .measurement_time(Duration::from_millis(5000));
    targets = bench_lots_of_vec9
}
criterion_main!(lots_of_vec9);
